import React from 'react';
import Head from 'next/head';
import Navbar from '../Navbar';

const Index = () => {
  return (
    <div>
      <Head>
        <title>Huseyin Topuz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}

export default Index